# Netlify Configuration
[build]
  publish = "."
  command = "echo 'No build step required - static site'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=600"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/upload/*"
  to = "/#upload"
  status = 200

[[redirects]]
  from = "/processing/*"
  to = "/#processing"
  status = 200

[[redirects]]
  from = "/results/*"
  to = "/#results"
  status = 200

[[redirects]]
  from = "/demo/*"
  to = "/#demo"
  status = 200

[[redirects]]
  from = "/history/*"
  to = "/#history"
  status = 200

[[redirects]]
  from = "/settings/*"
  to = "/#settings"
  status = 200

[[redirects]]
  from = "/help/*"
  to = "/#help"
  status = 200

[[redirects]]
  from = "/about/*"
  to = "/#about"
  status = 200

# Fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling (if needed in future)
[functions]

# Edge functions for enhanced performance
[[edge_functions]]
  function = "add-headers"
  path = "/*"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-sitemap"
  
  [plugins.inputs]
    buildDir = "."
    exclude = ["processing", "results", "history"]

# Environment variables (configured in Netlify UI)
# GOOGLE_ANALYTICS_ID = "G-XXXXXXXXXX"
# SITE_URL = "https://vat-calculator-pro.netlify.app"
