# Netlify Configuration for VAT Calculator Pro
# Simplified configuration to resolve parsing issues

[build]
  publish = "."
  command = "echo 'VAT Calculator Pro - Static site deployment'"

[build.environment]
  NODE_VERSION = "18"
  ENVIRONMENT = "production"

# Branch-specific deployments
[context.production]
  publish = "."
  command = "echo 'Production deployment'"

[context.deploy-preview]
  publish = "."
  command = "echo 'Preview deployment'"

[context.branch-deploy]
  publish = "."
  command = "echo 'Branch deployment'"

# Redirects
[[redirects]]
  from = "https://vat-calculator-pro.netlify.app/*"
  to = "https://vat-calculator-pro.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/upload"
  to = "/upload/"
  status = 301

[[redirects]]
  from = "/processing"
  to = "/processing/"
  status = 301

[[redirects]]
  from = "/results"
  to = "/results/"
  status = 301

[[redirects]]
  from = "/demo"
  to = "/demo/"
  status = 301

[[redirects]]
  from = "/help"
  to = "/help/"
  status = 301

[[redirects]]
  from = "/about"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/settings"
  to = "/settings/"
  status = 301

[[redirects]]
  from = "/history"
  to = "/history/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# HTML files - no long-term caching
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# CSS files - long-term caching
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# JavaScript files - long-term caching
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Image files - long-term caching
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Excel and CSV files
[[headers]]
  for = "*.xlsx"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

[[headers]]
  for = "*.csv"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "text/csv; charset=utf-8"

# Build processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
